Fix invalid poly. declaration (#2098)
Fixes the following issue deteced by NAG

Error: io/mean_field_output.f90, line 87: Polymorphic array MEAN_FIELDS
that is not deferred-shape, assumed-shape, or assumed-rank, is not yet
supported